# backend/config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    # Configuration pour extraire le token depuis les cookies
    token_extractors:
        # Désactiver l'Authorization header si vous voulez utiliser uniquement les cookies
        authorization_header:
            enabled: false
        # Activer l'extraction depuis les cookies
        cookie:
            enabled: true
            name: 'jwt'

    # Configuration pour définir automatiquement les cookies httpOnly
    set_cookies:
        jwt:
            lifetime: 3600        # Durée de vie du cookie (en secondes)
            samesite: 'lax'       # Protection CSRF (lax, strict, none)
            path: '/'             # Chemin du cookie
            domain: null          # Domaine (null = domaine actuel)
            httpOnly: true        # 🔒 Cookie httpOnly (sécurité XSS)
            secure: true          # 🔒 Cookie sécurisé (HTTPS uniquement)
            partitioned: false    # Pour Symfony 6.4+