nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['https://app.stadi.ddev.site', 'http://localhost:3000', 'http://localhost:5173']
            allow_headers: ['X-Custom-Auth', 'Authorization', 'Content-Type', 'Accept']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_credentials: true
            max_age: 3600
