framework:
    serializer:
        mapping:
            paths: ['%kernel.project_dir%/config/serialization']
        default_context:
            enable_max_depth: true
            ignored_attributes: ['__initializer__', '__cloner__', '__isInitialized__']
