name: stadi
type: symfony
docroot: backend/public
php_version: '8.3'
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: ['api.stadidev', 'app.stadidev']
additional_fqdns: []
database:
  type: postgres
  version: '17'
use_dns_when_possible: true
composer_version: '2'
web_environment: []
corepack_enable: false
